[BREAKING CHANGE] Allow slash in kv path
nmaupu/vault-secret pull request #6
Opened 2019-07-31 19:06 UTC by vizv

instead of spliting path and use the first token as KV path, define a separate field for KV path which allows slash in the path

2019-07-31 21:09 UTC, nmaupu requested changes

2019-07-31 21:09 UTC, nmaupu commented on pkg/vault/utils.go
> +	p := kvPath + "/" + secretPath
`path.Join` instead ?

2019-08-01 20:12 UTC, vizv commented on pkg/vault/utils.go
> +	p := kvPath + "/" + secretPath
good point, i'll change that

2019-08-08 17:04 UTC, vizv commented
@nmaupu any update on this?

2019-08-08 17:14 UTC, nmaupu approved these changes

2019-08-08 17:15 UTC, merged